name: 'NPM Custom Actions'
description: 'Greet someone'
inputs:
    path_of_folder:
    description: 'The path to cache'
    required: true
runs:
  using: "Installing and Caching NPM Packages"
  steps:
    - name: cache NPM Dependencies
      uses: actions/cache@v3
      with:
        path: ${{ inputs.path_of_folder }}
        key: ${{runner.os}}-node-modules-${{hashFiles('package-lock.json')}}
            
    - name: Install Dependencies
      run: npm install
      shell: bash