apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: solar-system
  namespace: _{_NAMESPACE_}_
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: _{_INGRESS_HOST_}_
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: solar-system
                port:
                  number: 3000
